CREATE DATABASE SUCOS_VENDAS;

CREATE TABLE [TABELA DE CLIENTES](
[CPF] [CHAR] (11),
[NOME] [VARCHAR] (100),
[ENDERECO1] [VARCHAR] (150),
[ENDERACO2] [VARCHAR] (150),
[BAIRRO] [VARCHAR] (40),
[CIDADE] [VARCHAR] (40),
[ESTADO] [CHAR] (2),
[CEP] [CHAR] (8),
[DATA_NASCIMENTO] [DATE],
[IDADE] [SMALLINT],
[SEXO] [CHAR] (1),
[LIMITE_CREDITO] [MONEY],
[VOLUME DE COMPRA] [FLOAT],
[PRIMEIRA_COMPRA] [BIT]
);

CREATE TABLE [TABELA DE VENDEDORES](
[MATRICULA] [VARCHAR] (5),
[NOME] [VARCHAR] (100),
[PERCENTUAL COMISSAO] [FLOAT],
);

CREATE TABLE [dbo].[TABELA DE PRODUTOS](
	[CODIGO DO PRODUTO] [varchar](20) NULL,
	[NOME DO PRODUTO] [varchar](150) NULL,
	[EMBALAGEM] [varchar](50) NULL,
	[TAMANHO] [varchar](50) NULL,
	[SABOR] [varchar](50) NULL,
	[PRECO DE LISTA] [smallmoney] NULL
) ON [PRIMARY]
GO



INSERT INTO [TABELA DE PRODUTOS](
[CODIGO DO PRODUTO],
[NOME DO PRODUTO],
EMBALAGEM,
TAMANHO,
SABOR,
[PRECO DE LISTA])
VALUES(
'1040107', 
'Light - 350 ml - Melância', 
'Lata', '350 ml', 
'Melância', 
4.56)


INSERT INTO [TABELA DE VENDEDORES](
[MATRICULA],
[NOME],
[PERCENTUAL COMISSAO])
VALUES(
'00235',
'Márcio Almeida Silva',
0.08)

INSERT INTO [TABELA DE VENDEDORES](
[MATRICULA],
[NOME],
[PERCENTUAL COMISSAO])
VALUES(
'00236',
'Cláudia Morais',
0.08)



INSERT INTO [TABELA DE PRODUTOS](
[CODIGO DO PRODUTO],
[NOME DO PRODUTO],
EMBALAGEM,
TAMANHO,
SABOR,
[PRECO DE LISTA])
VALUES(
'1037797', 
'Clean - 2 Litros - Laranja', 
'PET', '2 Litros', 
'Laranja', 
16.01),
('1000889', 
'Sabor da Montanha - 700 ml - Uva', 
'Garrafa', '700 ml', 
'Uva', 
6.31);


UPDATE [TABELA DE PRODUTOS]
SET EMBALAGEM = 'LATA',
[PRECO DE LISTA] = 2.46
WHERE [CODIGO DO PRODUTO] = '544931'

UPDATE [TABELA DE PRODUTOS]
SET EMBALAGEM = 'GARRAFA'
WHERE [CODIGO DO PRODUTO] = '1078680'



DELETE FROM [TABELA DE PRODUTOS]
WHERE [CODIGO DO PRODUTO] = '1078680'

ALTER TABLE [TABELA DE PRODUTOS]
ADD CONSTRAINT PK_TABELA_DE_PRODUTOS
PRIMARY KEY CLUSTERED (
[CODIGO DO PRODUTO]
);

ALTER TABLE [TABELA DE PRODUTOS]
ALTER COLUMN [CODIGO DO PRODUTO]
VARCHAR(20) NOT NULL;


ALTER TABLE [TABELA DE CLIENTES]
ALTER COLUMN [CPF]
CHAR(11) NOT NULL;

ALTER TABLE [TABELA DE CLIENTES]
ADD CONSTRAINT PK_TABELA_DE_CLIENTES
PRIMARY KEY CLUSTERED (
[CPF]
);

INSERT INTO [dbo].[TABELA DE CLIENTES]
           ([CPF]
           ,[NOME]
           ,[ENDERECO1]
           ,[ENDERACO2]
           ,[BAIRRO]
           ,[CIDADE]
           ,[ESTADO]
           ,[CEP]
           ,[DATA_NASCIMENTO]
           ,[IDADE]
           ,[SEXO]
           ,[LIMITE_CREDITO]
           ,[VOLUME DE COMPRA]
           ,[PRIMEIRA_COMPRA])
     VALUES
           ('00383454802'
           ,'João da Silva'
           ,'Rua Projetada A'
           ,'Número 233'
           ,'Copacabana'
           ,'Rio de Janeiro'
           ,'RJ'
           ,'20000000'
           ,'1965-03-21'
           ,55
           ,'M'
           ,20000.00
           ,3000.23
           ,1)

SELECT [CPF]
      ,[NOME]
      ,[ENDERECO1]
      ,[ENDERECO2]
      ,[BAIRRO]
      ,[CIDADE]
      ,[ESTADO]
      ,[CEP]
      ,[DATA DE NASCIMENTO]
      ,[IDADE]
      ,[SEXO]
      ,[LIMITE DE CREDITO]
      ,[VOLUME DE COMPRA]
      ,[PRIMEIRA COMPRA]
  FROM [dbo].[TABELA DE CLIENTES]

SELECT * FROM [TABELA DE CLIENTES]

SELECT [CPF] AS [CPF DO CLIENTE]
      ,[NOME] AS [NOME CLIENTE]
  FROM [dbo].[TABELA DE CLIENTES]



  SELECT * FROM [TABELA DE PRODUTOS] WHERE [CODIGO DO PRODUTO] = '1000889'

  SELECT * FROM [TABELA DE PRODUTOS] WHERE [SABOR] = 'Uva'

  SELECT * FROM [TABELA DE PRODUTOS] WHERE [CODIGO DO PRODUTO] = 'Limão'

  SELECT * FROM [TABELA DE PRODUTOS] WHERE EMBALAGEM = 'PET'

  SELECT * FROM [TABELA DE PRODUTOS] WHERE [PRECO DE LISTA] = 4.555
  
  SELECT * FROM [TABELA DE PRODUTOS] WHERE [PRECO DE LISTA] < 10

  SELECT * FROM [TABELA DE PRODUTOS] WHERE [PRECO DE LISTA] > 10
  
  SELECT * FROM [TABELA DE PRODUTOS] WHERE [PRECO DE LISTA] <= 4.555

  SELECT * FROM [TABELA DE PRODUTOS] WHERE [PRECO DE LISTA] >= 4.555

  SELECT * FROM [TABELA DE PRODUTOS] WHERE EMBALAGEM <= 'Lata'

  SELECT * FROM [TABELA DE PRODUTOS] WHERE EMBALAGEM <> 'Lata'

  SELECT * FROM [TABELA DE CLIENTES] WHERE [DATA DE NASCIMENTO] = '1995-09-11'

  SELECT * FROM [TABELA DE CLIENTES] WHERE [DATA DE NASCIMENTO] >= '1995-09-11'

  SELECT * FROM [TABELA DE CLIENTES] WHERE [DATA DE NASCIMENTO] <= '1995-09-11'

  SELECT * FROM [TABELA DE CLIENTES] WHERE YEAR([DATA DE NASCIMENTO]) = 1995

  SELECT * FROM [TABELA DE CLIENTES] WHERE YEAR([DATA DE NASCIMENTO]) < 1995

  SELECT * FROM [TABELA DE CLIENTES] WHERE MONTH([DATA DE NASCIMENTO]) = 12

  SELECT * FROM [TABELA DE CLIENTES] WHERE DAY([DATA DE NASCIMENTO]) = 11

  SELECT * FROM [TABELA DE PRODUTOS] WHERE [SABOR] = 'Manga' OR [TAMANHO] = '700 ml' 

SELECT * FROM [TABELA DE PRODUTOS] WHERE [SABOR] = 'Manga' AND [TAMANHO] = '700 ml' 

SELECT * FROM [TABELA DE PRODUTOS] WHERE NOT ([SABOR] = 'Manga' AND [TAMANHO] = '700 ml')

SELECT * FROM [TABELA DE PRODUTOS] WHERE NOT ([SABOR] = 'Manga' OR [TAMANHO] = '700 ml')

SELECT * FROM [TABELA DE PRODUTOS] WHERE [SABOR] = 'Manga' AND NOT ( [TAMANHO] = '700 ml')

SELECT * FROM [TABELA DE PRODUTOS] WHERE [SABOR] IN ('Manga', 'Laranja')

SELECT * FROM [TABELA DE PRODUTOS] WHERE [SABOR] = 'Manga' OR [SABOR] ='Laranja'

SELECT * FROM [TABELA DE PRODUTOS] WHERE [SABOR] NOT IN ('Manga', 'Laranja')

SELECT * FROM [TABELA DE PRODUTOS] WHERE NOT ([SABOR] = 'Manga' OR [SABOR] ='Laranja')

SELECT * FROM [TABELA DE PRODUTOS] WHERE [SABOR] IN ('Manga', 'Laranja') AND [PREÇO DE LISTA] > 10

SELECT * FROM [TABELA DE PRODUTOS] WHERE [SABOR] IN ('Manga', 'Laranja') AND [PREÇO DE LISTA] BETWEEN 10 AND 13

SELECT * FROM [TABELA DE PRODUTOS] WHERE [SABOR] IN ('Manga', 'Laranja') AND [PREÇO DE LISTA] >= 10 AND [PREÇO DE LISTA] <= 13

SELECT * FROM [TABELA DE PRODUTOS]

SELECT * FROM [TABELA DE PRODUTOS] WHERE [NOME DO PRODUTO] LIKE '%Litros%'

SELECT * FROM [TABELA DE PRODUTOS] WHERE [NOME DO PRODUTO] LIKE 'Litros%'

SELECT * FROM [TABELA DE PRODUTOS] WHERE [NOME DO PRODUTO] LIKE '%Litros%' AND [SABOR] = 'Laranja'

SELECT EMBALAGEM, TAMANHO FROM [TABELA DE PRODUTOS]

SELECT DISTINCT EMBALAGEM, TAMANHO FROM [TABELA DE PRODUTOS]

SELECT DISTINCT EMBALAGEM, TAMANHO FROM [TABELA DE PRODUTOS] WHERE
[SABOR] = 'Laranja'

SELECT DISTINCT EMBALAGEM, TAMANHO, SABOR FROM [TABELA DE PRODUTOS]

SELECT * FROM [TABELA DE PRODUTOS]

SELECT TOP 3 * FROM [TABELA DE PRODUTOS]

SELECT * FROM [TABELA DE PRODUTOS] WHERE [SABOR] = 'Laranja'

SELECT TOP 3 * FROM [TABELA DE PRODUTOS] WHERE [SABOR] = 'Laranja'

SELECT EMBALAGEM, TAMANHO FROM [TABELA DE PRODUTOS]

SELECT DISTINCT EMBALAGEM, TAMANHO FROM [TABELA DE PRODUTOS]

SELECT DISTINCT TOP 3 EMBALAGEM, TAMANHO FROM [TABELA DE PRODUTOS]

SELECT * FROM [dbo].[TABELA DE PRODUTOS]

SELECT * FROM [TABELA DE PRODUTOS] ORDER BY [PREÇO DE LISTA]

SELECT * FROM [TABELA DE PRODUTOS] ORDER BY [PREÇO DE LISTA] DESC

SELECT * FROM [TABELA DE PRODUTOS] ORDER BY [NOME DO PRODUTO]

SELECT [EMBALAGEM], [NOME DO PRODUTO] FROM [TABELA DE PRODUTOS] 
ORDER BY [EMBALAGEM], [NOME DO PRODUTO]

SELECT [EMBALAGEM], [NOME DO PRODUTO] FROM [TABELA DE PRODUTOS] ORDER BY [EMBALAGEM] DESC, [NOME DO PRODUTO] ASC

SELECT * FROM [dbo].[TABELA DE CLIENTES]

SELECT ESTADO,  [LIMITE DE CREDITO] FROM [dbo].[TABELA DE CLIENTES]

SELECT ESTADO, SUM([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES] GROUP BY ESTADO

SELECT ESTADO, AVG([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES] GROUP BY ESTADO

SELECT EMBALAGEM, MAX([PREÇO DE LISTA]) FROM [TABELA DE PRODUTOS] GROUP BY EMBALAGEM

SELECT EMBALAGEM, MIN([PREÇO DE LISTA]) FROM [TABELA DE PRODUTOS] GROUP BY EMBALAGEM

SELECT [NOME DO PRODUTO], EMBALAGEM  FROM [TABELA DE PRODUTOS] ORDER BY EMBALAGEM

SELECT EMBALAGEM, COUNT(*) FROM [TABELA DE PRODUTOS] GROUP BY EMBALAGEM

SELECT BAIRRO, SUM([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES] WHERE [ESTADO]  = 'SP' GROUP BY BAIRRO

SELECT BAIRRO, SUM([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES] WHERE [ESTADO]  = 'SP' GROUP BY BAIRRO ORDER BY BAIRRO DESC

SELECT BAIRRO, ESTADO, SUM([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES] WHERE [ESTADO]  = 'SP' GROUP BY BAIRRO, ESTADO
